from fastapi import FastAPI, HTTPException
from typing import Optional
import uvicorn

app = FastAPI(title="Sentinel API")

# Mock database for example purposes
database = {}

@app.get("/")
def health_check():
    return {"status": "Sentinel is Online"}

@app.post("/scrape")
def scrape_url(url: str):
    try:
        # In a real app, your scraping/AI logic goes here
        # For now, we simulate a successful scrape
        summary_data = {
            "title": url.split("/")[-1].replace("_", " "),
            "summary": "This is a placeholder summary generated by the Sentinel system.",
            "url": url
        }
        database[url] = summary_data
        return summary_data
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/summaries")
def get_summaries(url: Optional[str] = None):
    """URL is now optional. If provided, filters by URL. Otherwise, returns all."""
    if url:
        if url in database:
            return database[url]
        return {"error": f"Scrape the URL first using /scrape?url={url}"}
    
    # Return everything if no URL provided
    return list(database.values())

if __name__ == "__main__":
    uvicorn.run(app, host="127.0.0.1", port=8000)